**Question 1**

In [4]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
import pandas as pd

# Define the sentences S1, S2, S3
sentences = [
    "data science is one of the most important courses in computer science",
    "this is one of the best data science courses",
    "the data scientists perform data analysis"
]

# Bag of Words (BoW)
vectorizer_bow = CountVectorizer()
bow_matrix = vectorizer_bow.fit_transform(sentences)
bow_df = pd.DataFrame(bow_matrix.toarray(), columns=vectorizer_bow.get_feature_names_out())
print("Bag of Words (BoW):")
print(bow_df)

# Term Frequency (TF)
vectorizer_tf = TfidfVectorizer(use_idf=False)
tf_matrix = vectorizer_tf.fit_transform(sentences)
tf_df = pd.DataFrame(tf_matrix.toarray(), columns=vectorizer_tf.get_feature_names_out())
print("\nTerm Frequency (TF):")
print(tf_df)

# Inverse Document Frequency (IDF)
vectorizer_idf = TfidfVectorizer(use_idf=True)
idf_matrix = vectorizer_idf.fit_transform(sentences)
idf_df = pd.DataFrame(idf_matrix.toarray(), columns=vectorizer_idf.get_feature_names_out())
print("\nInverse Document Frequency (IDF):")
print(idf_df)

# TF-IDF
vectorizer_tfidf = TfidfVectorizer(use_idf=True)
tfidf_matrix = vectorizer_tfidf.fit_transform(sentences)
tfidf_df = pd.DataFrame(tfidf_matrix.toarray(), columns=vectorizer_tfidf.get_feature_names_out())
print("\nTF-IDF:")
print(tfidf_df)


Bag of Words (BoW):
   analysis  best  computer  courses  data  important  in  is  most  of  one  \
0         0     0         1        1     1          1   1   1     1   1    1   
1         0     1         0        1     1          0   0   1     0   1    1   
2         1     0         0        0     2          0   0   0     0   0    0   

   perform  science  scientists  the  this  
0        0        2           0    1     0  
1        0        1           0    1     1  
2        1        0           1    1     0  

Term Frequency (TF):
   analysis      best  computer   courses      data  important        in  \
0  0.000000  0.000000  0.267261  0.267261  0.267261   0.267261  0.267261   
1  0.000000  0.333333  0.000000  0.333333  0.333333   0.000000  0.000000   
2  0.353553  0.000000  0.000000  0.000000  0.707107   0.000000  0.000000   

         is      most        of       one   perform   science  scientists  \
0  0.267261  0.267261  0.267261  0.267261  0.000000  0.534522    0.000000  

**Question 2**

In [5]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity, manhattan_distances, euclidean_distances

# Define the sentences S1, S2, S3
sentences = [
    "data science is one of the most important courses in computer science",
    "this is one of the best data science courses",
    "the data scientists perform data analysis"
]

# TF-IDF vectorization
vectorizer = TfidfVectorizer()
tfidf_matrix = vectorizer.fit_transform(sentences)

# Compute distances
cosine_sim = cosine_similarity(tfidf_matrix)
manhattan_dist = manhattan_distances(tfidf_matrix)
euclidean_dist = euclidean_distances(tfidf_matrix)

# Display the results
print("Cosine Similarity:")
print(cosine_sim)

print("\nManhattan Distance:")
print(manhattan_dist)

print("\nEuclidean Distance:")
print(euclidean_dist)


Cosine Similarity:
[[1.         0.57732419 0.15733751]
 [0.57732419 1.         0.20321737]
 [0.15733751 0.20321737 1.        ]]

Manhattan Distance:
[[0.         2.73556468 4.60822682]
 [2.73556468 0.         4.14553005]
 [4.60822682 4.14553005 0.        ]]

Euclidean Distance:
[[0.         0.91943005 1.29820067]
 [0.91943005 0.         1.26236494]
 [1.29820067 1.26236494 0.        ]]
